spring:
  application:
    name: Produtos API
  datasource:
    url: 'jdbc:h2:mem:products'
    username: 'lir'
    password: '123'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

    # ^ access DBMS from browser http://localhost:8080/h2-console #